# Generated by Django 5.2.6 on 2025-10-13 23:42

import Clash.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preco_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Cartao', models.CharField(max_length=50)),
                ('Numero_Cartao', models.CharField(max_length=16)),
                ('Nome_Cartao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Clash.models.gerar_caminho_imagem_produto)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='tbJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=50)),
                ('Data_Nascimento', models.DateField(blank=True, null=True)),
                ('Idade', models.PositiveIntegerField(blank=True, null=True)),
                ('sobre', models.TextField()),
                ('trofeus', models.IntegerField(default=0)),
                ('Foto_Jogador', models.ImageField(blank=True, null=True, upload_to=Clash.models.gerar_caminho_foto_jogador)),
            ],
        ),
        migrations.CreateModel(
            name='tbPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Prevista', models.DateTimeField()),
                ('Time_Adversario', models.CharField(max_length=100)),
                ('Modalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbfoto')),
            ],
            options={
                'verbose_name': 'Especificação',
                'verbose_name_plural': 'Especificações',
            },
        ),
        migrations.CreateModel(
            name='tbNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('TextoHTML', models.TextField()),
                ('Partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clash.tbpartida')),
            ],
        ),
        migrations.CreateModel(
            name='tbJogador_Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbJogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbjogador')),
                ('tbPartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbpartida')),
            ],
        ),
        migrations.CreateModel(
            name='tbProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificacoes', models.ManyToManyField(related_name='produtos_especificados', through='Clash.tbEspecifica', to='Clash.tbfoto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='tbfoto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foto', to='Clash.tbproduto'),
        ),
        migrations.AddField(
            model_name='tbespecifica',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbproduto'),
        ),
        migrations.CreateModel(
            name='tbCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Clash.tbcarrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbproduto')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Itens de Compra',
            },
        ),
        migrations.CreateModel(
            name='tbStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('embed', models.TextField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissoes', to='Clash.tbpartida')),
            ],
            options={
                'verbose_name': 'Transmissão',
                'verbose_name_plural': 'Transmissões',
            },
        ),
        migrations.CreateModel(
            name='tbUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Data_Nascimento', models.DateField(blank=True, null=True)),
                ('Foto_Perfil', models.ImageField(blank=True, null=True, upload_to=Clash.models.gerar_caminho_foto_perfil)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='tbEdita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Edicao', models.DateField(auto_now_add=True)),
                ('tbNoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clash.tbnoticia')),
                ('tbUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tbcarrinho',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tbespecifica',
            unique_together={('produto', 'foto')},
        ),
    ]
