# Generated by Django 5.2.6 on 2025-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbjogador',
            name='Idade',
        ),
        migrations.AddField(
            model_name='tbespecifica',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
