# Generated by Django 5.2.6 on 2025-11-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0002_remove_tbjogador_idade_tbespecifica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbproduto',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
