# Generated by Django 5.2.6 on 2025-11-23 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0004_tbcompra_especificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbTipoEspecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tbespecifica',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clash.tbtipoespecificacao'),
        ),
    ]
