# Generated by Django 5.2.6 on 2025-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0005_tbtipoespecificacao_tbespecifica_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcompra',
            name='especificacao',
        ),
        migrations.AddField(
            model_name='tbcompra',
            name='especificacoes',
            field=models.ManyToManyField(blank=True, to='Clash.tbespecifica'),
        ),
    ]
