# Generated by Django 5.2.6 on 2025-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0007_tbpedido_tbitempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbproduto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
