# Generated by Django 5.2.6 on 2025-12-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clash', '0008_tbproduto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcarrinho',
            name='Preco_Total',
        ),
    ]
